"""Dataset loading, schema validation and duplicate handling.

Design rules for this module:

* The caller must state *which* file is loaded and *what* it claims to be
  (``source``). Nothing is downloaded and nothing is silently substituted.
* The Kaggle release (``creditcard.csv``) contains ``Time``; the OpenML mirror
  (data id 1597) omits it. Because ``Time`` is a model input in the historical
  experiment, a ``kaggle`` dataset without ``Time`` is rejected and an
  ``openml`` dataset is recorded as having a different feature schema.
* Validation happens on the raw values *before* any lossy conversion so that
  labels such as ``0.7`` or ``2`` cannot be truncated into a valid class.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

import numpy as np
import pandas as pd

LABEL_COLUMN = "Class"
TIME_COLUMN = "Time"
PCA_FEATURES = [f"V{i}" for i in range(1, 29)]
REQUIRED_FEATURES = PCA_FEATURES + ["Amount"]
ROW_ID_COLUMN = "row_id"

Source = Literal["kaggle", "openml", "synthetic"]
DuplicatePolicy = Literal["drop_exact", "keep"]

# Resource limits applied *before* the CSV is parsed (size) and *while* it is
# parsed (rows). The defaults comfortably cover the Kaggle release
# (~150 MB, 284,807 rows) and can be raised per call / via the CLI.
DEFAULT_MAX_DATASET_BYTES = 2 * 1024 * 1024 * 1024
DEFAULT_MAX_DATASET_ROWS = 5_000_000


class DatasetTooLargeError(ValueError):
    """Raised when a dataset exceeds the configured byte or row limit."""

SOURCE_DESCRIPTIONS: dict[str, str] = {
    "kaggle": (
        "ULB Credit Card Fraud dataset, authoritative Kaggle release "
        "(https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud); includes Time."
    ),
    "openml": (
        "OpenML mirror, data id 1597; omits the Time column, so its feature "
        "schema differs from the Kaggle release used in the historical experiment."
    ),
    "synthetic": "Deterministic synthetic fixture generated by fraud_pipeline.synthetic.",
}


class SchemaError(ValueError):
    """Raised when a dataset does not satisfy the expected schema."""


@dataclass(frozen=True)
class DatasetInfo:
    """Provenance and quality facts recorded for a loaded dataset."""

    path: str
    source: str
    source_description: str
    sha256: str
    size_bytes: int
    features: list[str]
    has_time: bool
    ignored_columns: list[str]
    raw_rows: int
    raw_class_counts: dict[int, int]
    missing_values: int
    duplicate_policy: str
    duplicates_removed: int
    duplicates_retained: int
    rows: int
    class_counts: dict[int, int]
    fraud_prevalence: float


@dataclass
class Dataset:
    """A validated, de-duplicated frame indexed by stable ``row_id``."""

    frame: pd.DataFrame
    info: DatasetInfo
    features: list[str] = field(init=False)

    def __post_init__(self) -> None:
        self.features = list(self.info.features)

    @property
    def X(self) -> pd.DataFrame:
        return self.frame[self.features]

    @property
    def y(self) -> pd.Series:
        return self.frame[LABEL_COLUMN]


def sha256_file(path: Path, chunk_size: int = 1 << 20) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _class_counts(labels: pd.Series) -> dict[int, int]:
    counts = labels.value_counts().sort_index()
    return {int(k): int(v) for k, v in counts.items()}


def validate_labels(raw: pd.Series) -> pd.Series:
    """Return an ``int`` label series, rejecting anything that is not exactly 0/1.

    Validation is performed on the raw values: ``0.7`` or ``2`` are rejected
    instead of being truncated by ``astype(int)``; string labels are accepted
    only if every value is literally ``"0"`` or ``"1"`` (the OpenML mirror
    exposes ``Class`` as a categorical of strings).
    """
    if raw.isna().any():
        raise SchemaError(f"{LABEL_COLUMN} contains {int(raw.isna().sum())} missing values")
    if pd.api.types.is_bool_dtype(raw):
        return raw.astype(int)
    if pd.api.types.is_numeric_dtype(raw):
        values = raw.to_numpy(dtype=float)
        if not np.all(np.isfinite(values)):
            raise SchemaError(f"{LABEL_COLUMN} contains non-finite values")
        bad = ~np.isin(values, (0.0, 1.0))
        if bad.any():
            examples = sorted(set(values[bad].tolist()))[:5]
            raise SchemaError(
                f"{LABEL_COLUMN} must contain only 0 and 1; found {examples}"
            )
        return pd.Series(values.astype(int), index=raw.index, name=LABEL_COLUMN)
    text = raw.astype(str).str.strip()
    bad_text = sorted(set(text[~text.isin(["0", "1"])].tolist()))
    if bad_text:
        raise SchemaError(
            f"{LABEL_COLUMN} must contain only 0 and 1; found {bad_text[:5]}"
        )
    return text.astype(int).rename(LABEL_COLUMN)


def validate_frame(frame: pd.DataFrame, source: str) -> tuple[pd.DataFrame, list[str], list[str]]:
    """Validate a raw frame and return ``(clean_frame, features, ignored_columns)``.

    The returned frame contains the ordered feature columns plus an integer
    ``Class`` column and keeps the caller's index.
    """
    if source not in SOURCE_DESCRIPTIONS:
        raise SchemaError(f"Unknown source {source!r}; expected one of {sorted(SOURCE_DESCRIPTIONS)}")

    missing = [c for c in REQUIRED_FEATURES + [LABEL_COLUMN] if c not in frame.columns]
    if missing:
        raise SchemaError(f"Dataset is missing required columns: {missing}")

    has_time = TIME_COLUMN in frame.columns
    if source == "kaggle" and not has_time:
        raise SchemaError(
            "source='kaggle' requires the Time column present in the Kaggle release; "
            "pass source='openml' if this is the OpenML mirror (which omits Time)."
        )

    features = ([TIME_COLUMN] if has_time else []) + REQUIRED_FEATURES
    ignored = [c for c in frame.columns if c not in features and c != LABEL_COLUMN]

    non_numeric = [c for c in features if not pd.api.types.is_numeric_dtype(frame[c])]
    if non_numeric:
        raise SchemaError(f"Feature columns must be numeric; non-numeric: {non_numeric}")

    X = frame[features].astype(float)
    if X.isna().any().any():
        counts = X.isna().sum()
        raise SchemaError(
            f"Feature columns contain missing values: {counts[counts > 0].to_dict()}"
        )
    finite = np.isfinite(X.to_numpy())
    if not finite.all():
        bad_columns = [c for c, ok in zip(features, finite.all(axis=0)) if not ok]
        raise SchemaError(f"Feature columns contain non-finite values: {bad_columns}")

    labels = validate_labels(frame[LABEL_COLUMN])
    present = sorted(labels.unique().tolist())
    if present != [0, 1]:
        raise SchemaError(
            f"Exactly two classes (0 and 1) must be present; found {present}"
        )

    clean = X.copy()
    clean[LABEL_COLUMN] = labels.to_numpy()
    return clean, features, ignored


def deduplicate(frame: pd.DataFrame, policy: DuplicatePolicy) -> tuple[pd.DataFrame, int, int]:
    """Apply the duplicate policy and return ``(frame, rows_removed, rows_retained)``.

    ``drop_exact`` removes rows whose *entire* row (all features and the
    label) is identical to an earlier row, keeping the first occurrence. Rows
    that share features but disagree on ``Class`` are not duplicates and are
    kept. This is the policy used by the historical experiment (1,081 rows
    removed from the Kaggle release). ``keep`` performs no removal but still
    reports how many exact duplicates remain so callers can refuse to
    evaluate a split that would treat identical rows as independent.
    """
    if policy not in ("drop_exact", "keep"):
        raise ValueError(f"Unknown duplicate policy {policy!r}")
    mask = frame.duplicated(keep="first")
    duplicates = int(mask.sum())
    if policy == "keep":
        return frame, 0, duplicates
    return frame.loc[~mask], duplicates, 0


def load_dataset(
    path: str | Path,
    source: Source,
    duplicate_policy: DuplicatePolicy = "drop_exact",
    max_bytes: int = DEFAULT_MAX_DATASET_BYTES,
    max_rows: int = DEFAULT_MAX_DATASET_ROWS,
) -> Dataset:
    """Load and validate a CSV dataset from an explicit path and declared source.

    The file size is checked against ``max_bytes`` before parsing and the
    parser stops after ``max_rows + 1`` rows, so an oversized input fails with
    :class:`DatasetTooLargeError` instead of exhausting memory. The resulting
    frame is indexed by ``row_id`` = 0-based position of the row in the CSV,
    which stays stable through de-duplication and splitting. ``info.path`` is
    the absolute, resolved location.
    """
    path = Path(path).expanduser()
    if not path.is_file():
        raise FileNotFoundError(f"Dataset file not found: {path}")
    path = path.resolve()
    size = path.stat().st_size
    if size > max_bytes:
        raise DatasetTooLargeError(f"Dataset is {size:,} bytes, above the limit of {max_bytes:,} bytes")

    raw = pd.read_csv(path, nrows=max_rows + 1)
    if len(raw) > max_rows:
        raise DatasetTooLargeError(f"Dataset has more than {max_rows:,} rows (limit {max_rows:,})")
    raw.index = pd.RangeIndex(len(raw), name=ROW_ID_COLUMN)
    clean, features, ignored = validate_frame(raw, source)

    raw_counts = _class_counts(clean[LABEL_COLUMN])
    deduped, removed, retained = deduplicate(clean, duplicate_policy)
    counts = _class_counts(deduped[LABEL_COLUMN])
    if sorted(counts) != [0, 1]:
        raise SchemaError(f"Both classes must survive de-duplication; found {sorted(counts)}")

    info = DatasetInfo(
        path=str(path),
        source=source,
        source_description=SOURCE_DESCRIPTIONS[source],
        sha256=sha256_file(path),
        size_bytes=path.stat().st_size,
        features=features,
        has_time=TIME_COLUMN in features,
        ignored_columns=ignored,
        raw_rows=int(len(raw)),
        raw_class_counts=raw_counts,
        missing_values=int(raw[features + [LABEL_COLUMN]].isna().sum().sum()),
        duplicate_policy=duplicate_policy,
        duplicates_removed=removed,
        duplicates_retained=retained,
        rows=int(len(deduped)),
        class_counts=counts,
        fraud_prevalence=float(deduped[LABEL_COLUMN].mean()),
    )
    return Dataset(frame=deduped, info=info)
